[package]
name = "gittr"
description = "Gittr is a self-hosted git platform for small, stealthy teams."
version = "0.1.0"
edition = "2024"
authors = ["Lucas Morais <lucas.morais@lsconsult.tech>"]
categories = ["git", "tooling"]
keywords = ["git", "self-hosted", "server"]
repository = "https://github.com/lmorais-dev/gittr"
homepage = "https://github.com/lmorais-dev/gittr"
documentation = "https://github.com/lmorais-dev/gittr/wiki"
readme = "README.md"
license = "MIT"
publish = true

[dependencies]
